use UNIVER;

select
	FACULTY.FACULTY as Факультет,
	PULPIT.PULPIT as Кафедра,
	PROGRESS.SUBJECT as Дисциплина,
	PROFESSION.PROFESSION_NAME as Специальность,
	STUDENT.NAME as [Имя студента],
	CASE
		when (PROGRESS.NOTE = 6) then 'Шесть'
		when (PROGRESS.NOTE = 7) then 'Семь'
		when (PROGRESS.NOTE = 8) then 'Восемь'
	END Оценка
FROM STUDENT
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION
WHERE PROGRESS.NOTE BETWEEN 6 AND 8;

-- task five
select
	FACULTY.FACULTY as Факультет,
	PULPIT.PULPIT as Кафедра,
	PROGRESS.SUBJECT as Дисциплина,
	PROFESSION.PROFESSION_NAME as Специальность,
	STUDENT.NAME as [Имя студента],
	CASE
		when (PROGRESS.NOTE = 6) then 'Шесть'
		when (PROGRESS.NOTE = 7) then 'Семь'
		when (PROGRESS.NOTE = 8) then 'Восемь'
	END Оценка
FROM FACULTY, PULPIT, SUBJECT, GROUPS, PROFESSION, STUDENT
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE PROGRESS.SUBJECT = SUBJECT.SUBJECT AND
	  SUBJECT.PULPIT = PULPIT.PULPIT AND
	  PULPIT.FACULTY = FACULTY.FACULTY AND
	  STUDENT.IDGROUP = GROUPS.IDGROUP AND
	  GROUPS.PROFESSION = PROFESSION.PROFESSION AND
	  PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY
CASE
	WHEN (PROGRESS.NOTE = 7) then 1
	WHEN (PROGRESS.NOTE = 8) then 2
	WHEN (PROGRESS.NOTE = 6) then 3
END