use UNIVER;

-- task six
SELECT PULPIT.PULPIT_NAME as Кафедра, ISNULL(TEACHER.TEACHER_NAME, '***') as Преподаватель
FROM PULPIT LEFT OUTER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT;

-- task seven
SELECT PULPIT.PULPIT_NAME as Кафедра, ISNULL(TEACHER.TEACHER_NAME, '***') as Преподаватель
FROM PULPIT RIGHT OUTER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT;