use UNIVER;

select GROUPS.IDGROUP [Group ¹],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ÒÎÂ'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT;

select GROUPS.IDGROUP [Group ¹],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ÒÎÂ'
group by rollup(GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT);

select GROUPS.IDGROUP [Group ¹],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ÒÎÂ'
group by cube(GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT);