use UNIVER;

-- task 7
select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'าฮย'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT

UNION

select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ศา'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT;

select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'าฮย'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT

UNION ALL

select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ศา'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT;

-- task 8
select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'าฮย'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT

INTERSECT

select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ศา'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT;

-- task 9
select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'าฮย'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT

EXCEPT

select GROUPS.IDGROUP [Group น],
	   PROFESSION.PROFESSION_NAME [Profession],
	   PROGRESS.SUBJECT [Subject],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from PROFESSION
join FACULTY
on PROFESSION.FACULTY = FACULTY.FACULTY
join GROUPS
on GROUPS.PROFESSION = PROFESSION.PROFESSION
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ศา'
group by GROUPS.IDGROUP, PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT;