use UNIVER;

select FACULTY.FACULTY,
	   GROUPS.PROFESSION,
	   ( case
		   when GROUPS.YEAR_FIRST = 2010 then '4'
		   when GROUPS.YEAR_FIRST = 2011 then '3'
		   when GROUPS.YEAR_FIRST = 2012 then '2'
		   when GROUPS.YEAR_FIRST = 2013 then '1'
		   end
	   ) as [Course],
	   round(avg(cast(PROGRESS.NOTE as float(4))), 2) [Mark]
from FACULTY
join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.YEAR_FIRST;