use UNIVER;
go

create view AuditoriumsView as
select AUDITORIUM.AUDITORIUM,
	   AUDITORIUM.AUDITORIUM_TYPE,
	   AUDITORIUM.AUDITORIUM_CAPACITY,
	   AUDITORIUM.AUDITORIUM_NAME
from AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE like 'À %';