use UNIVER;
go

create view LectAuditoriumsView as
select AUDITORIUM.AUDITORIUM,
	   AUDITORIUM.AUDITORIUM_TYPE,
	   AUDITORIUM.AUDITORIUM_CAPACITY,
	   AUDITORIUM.AUDITORIUM_NAME
from AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE like 'À %' with check option;