use UNIVER;

select PULPIT.PULPIT_NAME, FACULTY.FACULTY
from PULPIT, FACULTY
where PULPIT.FACULTY = FACULTY.FACULTY and FACULTY.FACULTY in
(
	select distinct PROFESSION.FACULTY
	from PROFESSION
	where PROFESSION.PROFESSION_NAME like '%технологии%' or
		PROFESSION.PROFESSION_NAME like '%технология%'
);

select PULPIT.PULPIT_NAME, FACULTY.FACULTY
from PULPIT
join FACULTY
on PULPIT.FACULTY = FACULTY.FACULTY
where FACULTY.FACULTY in
(
	select distinct PROFESSION.FACULTY
	from PROFESSION
	where PROFESSION.PROFESSION_NAME like '%технологии%' or
		PROFESSION.PROFESSION_NAME like '%технология%'
);

select distinct PULPIT.PULPIT_NAME, FACULTY.FACULTY
from PULPIT
join FACULTY
on PULPIT.FACULTY = FACULTY.FACULTY
join PROFESSION
on FACULTY.FACULTY = PROFESSION.FACULTY
where PROFESSION.PROFESSION_NAME like '%технологии%' or
		PROFESSION.PROFESSION_NAME like '%технология%';