use UNIVER;

select AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM.AUDITORIUM_CAPACITY >= ALL
(
	select AUDITORIUM.AUDITORIUM_CAPACITY
	from AUDITORIUM
	where AUDITORIUM.AUDITORIUM_TYPE like 'À %'
);

select AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM.AUDITORIUM_CAPACITY >= ANY
(
	select AUDITORIUM.AUDITORIUM_CAPACITY
	from AUDITORIUM
	where AUDITORIUM.AUDITORIUM_TYPE like 'À %'
);