use UNIVER;

select A.AUDITORIUM_TYPE, A.AUDITORIUM_CAPACITY
from AUDITORIUM A
where A.AUDITORIUM_CAPACITY =
(
	select top(1) AUDITORIUM.AUDITORIUM_CAPACITY
	from AUDITORIUM
	where AUDITORIUM.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM_CAPACITY desc
);